### ISSUE TITLE
Bad file name

### ISSUE THREAD

**Issue by skaag** [Kaholo/kaholo-plugin-terraform-cli#1]
You need to rename the config file from `confing.json` to `config.json`.
Right now the plugin won't install:
```
Mar 29 22:15:04 keholo nodejs[8882]:   'Error while installing plugin',
Mar 29 22:15:04 keholo nodejs[8882]:   Error: No config file found!
```

**Comment by ilanyaniv** [comment]
You are correct.
We fixed this issue - currently it is in Develop branch, you are welcome to use it from there.
We will make sure it is pushed to master ASAP.
